# Paso 1

In [11]:
import pandas as pd 
df = pd.read_csv("weatherHistory.csv")
df = df.head(50)  # Eliminamos ejemplos para que se ejecute más deprisa en clase
df['Formatted Date'] = pd.to_datetime(df['Formatted Date'],  utc=True,)
df['year'] = df['Formatted Date'].dt.year
df['month'] = df['Formatted Date'].dt.month
df['day'] = df['Formatted Date'].dt.day
print(df.head())

             Formatted Date        Summary Precip Type  Temperature (C)  \
0 2006-03-31 22:00:00+00:00  Partly Cloudy        rain         9.472222   
1 2006-03-31 23:00:00+00:00  Partly Cloudy        rain         9.355556   
2 2006-04-01 00:00:00+00:00  Mostly Cloudy        rain         9.377778   
3 2006-04-01 01:00:00+00:00  Partly Cloudy        rain         8.288889   
4 2006-04-01 02:00:00+00:00  Mostly Cloudy        rain         8.755556   

   Apparent Temperature (C)  Humidity  Wind Speed (km/h)  \
0                  7.388889      0.89            14.1197   
1                  7.227778      0.86            14.2646   
2                  9.377778      0.89             3.9284   
3                  5.944444      0.83            14.1036   
4                  6.977778      0.83            11.0446   

   Wind Bearing (degrees)  Visibility (km)  Loud Cover  Pressure (millibars)  \
0                   251.0          15.8263         0.0               1015.13   
1                   259.0   

# Paso 2

In [12]:
import numpy as np

features = ["Humidity", 
            "Pressure (millibars)", "Visibility (km)",
            "Wind Bearing (degrees)"] 

X = df[features].to_numpy()
y = df["Temperature (C)"].to_numpy()



In [13]:
print(X)

[[8.90000e-01 1.01513e+03 1.58263e+01 2.51000e+02]
 [8.60000e-01 1.01563e+03 1.58263e+01 2.59000e+02]
 [8.90000e-01 1.01594e+03 1.49569e+01 2.04000e+02]
 [8.30000e-01 1.01641e+03 1.58263e+01 2.69000e+02]
 [8.30000e-01 1.01651e+03 1.58263e+01 2.59000e+02]
 [8.50000e-01 1.01666e+03 1.49569e+01 2.58000e+02]
 [9.50000e-01 1.01672e+03 9.98200e+00 2.59000e+02]
 [8.90000e-01 1.01684e+03 9.98200e+00 2.60000e+02]
 [8.20000e-01 1.01737e+03 9.98200e+00 2.59000e+02]
 [7.20000e-01 1.01722e+03 9.98200e+00 2.79000e+02]
 [6.70000e-01 1.01742e+03 1.12056e+01 2.90000e+02]
 [5.40000e-01 1.01774e+03 1.14471e+01 3.16000e+02]
 [5.50000e-01 1.01759e+03 1.12700e+01 2.81000e+02]
 [5.10000e-01 1.01748e+03 1.12700e+01 2.89000e+02]
 [4.70000e-01 1.01717e+03 1.14471e+01 2.62000e+02]
 [4.60000e-01 1.01647e+03 1.12700e+01 2.88000e+02]
 [6.00000e-01 1.01615e+03 1.12700e+01 2.51000e+02]
 [6.30000e-01 1.01617e+03 1.14471e+01 2.30000e+02]
 [6.90000e-01 1.01582e+03 1.12056e+01 1.63000e+02]
 [7.00000e-01 1.01583e+03 1.120

In [14]:
print(y)

[ 9.47222222  9.35555556  9.37777778  8.28888889  8.75555556  9.22222222
  7.73333333  8.77222222 10.82222222 13.77222222 16.01666667 17.14444444
 17.8        17.33333333 18.87777778 18.91111111 15.38888889 15.55
 14.25555556 13.14444444 11.55       11.18333333 10.11666667 10.2
 10.42222222  9.91111111 11.18333333  7.15555556  6.11111111  6.78888889
  7.26111111  7.8         9.87222222 12.22222222 15.09444444 17.35555556
 19.00555556 20.04444444 21.05       21.18333333 20.11666667 20.21666667
 20.         17.8        16.06111111 15.02222222 14.42222222 14.25555556
 13.77222222 13.28333333]


# Paso 3

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [16]:
print(X_train)


[[5.50000e-01 1.01759e+03 1.12700e+01 2.81000e+02]
 [8.30000e-01 1.01651e+03 1.58263e+01 2.59000e+02]
 [4.00000e-01 1.01222e+03 9.98200e+00 1.70000e+02]
 [8.20000e-01 1.01737e+03 9.98200e+00 2.59000e+02]
 [8.30000e-01 1.01641e+03 1.58263e+01 2.69000e+02]
 [9.50000e-01 1.01672e+03 9.98200e+00 2.59000e+02]
 [3.60000e-01 1.00926e+03 1.03523e+01 1.61000e+02]
 [5.80000e-01 1.00785e+03 1.58263e+01 1.59000e+02]
 [5.90000e-01 1.00789e+03 1.49569e+01 1.68000e+02]
 [4.60000e-01 1.01647e+03 1.12700e+01 2.88000e+02]
 [7.20000e-01 1.01722e+03 9.98200e+00 2.79000e+02]
 [6.00000e-01 1.01615e+03 1.12700e+01 2.51000e+02]
 [6.20000e-01 1.01440e+03 1.58263e+01 1.50000e+02]
 [6.10000e-01 1.01396e+03 9.98200e+00 1.51000e+02]
 [8.30000e-01 1.01416e+03 8.05000e+00 1.50000e+02]
 [8.90000e-01 1.01513e+03 1.58263e+01 2.51000e+02]
 [5.30000e-01 1.00811e+03 9.98200e+00 1.49000e+02]
 [7.90000e-01 1.01447e+03 1.58263e+01 1.80000e+02]
 [7.20000e-01 1.01425e+03 9.98200e+00 1.50000e+02]
 [8.50000e-01 1.01666e+03 1.495

In [17]:
print(X_test)

[[5.10000e-01 1.01748e+03 1.12700e+01 2.89000e+02]
 [3.70000e-01 1.01052e+03 9.98200e+00 1.79000e+02]
 [8.50000e-01 1.01452e+03 6.19850e+00 1.41000e+02]
 [5.50000e-01 1.00815e+03 9.98200e+00 1.59000e+02]
 [6.30000e-01 1.01617e+03 1.14471e+01 2.30000e+02]
 [6.00000e-01 1.00736e+03 1.58263e+01 1.60000e+02]
 [8.00000e-01 1.00871e+03 1.49569e+01 1.63000e+02]
 [6.60000e-01 1.01420e+03 1.58263e+01 1.49000e+02]
 [7.80000e-01 1.01424e+03 9.98200e+00 1.60000e+02]
 [7.00000e-01 1.01583e+03 1.12056e+01 1.39000e+02]]


# Paso 4

In [18]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

lin = LinearRegression()
lin.fit(X_train, y_train)
y_pred = lin.predict(X_test)

mse_lin = mean_squared_error(y_test, y_pred)
print("MSE (LinearRegression):", mse_lin)


MSE (LinearRegression): 2.07174962427052


# Paso 5

In [19]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

rf = RandomForestRegressor(random_state=42)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

mse_rf = mean_squared_error(y_test, y_pred)
print("MSE (RandomForest):", mse_rf)


MSE (RandomForest): 2.408980685185193


# Paso 6

In [34]:
from sklearn.svm import SVR
reg_svr = SVR()
reg_svr.fit(X_train, y_train)
y_pred = reg_svr.predict(X_test)

mse_svr = mean_squared_error(y_test, y_pred)
print("MSE (SVR):", mse_svr)

MSE (SVR): 15.028923232963518


# Paso 7

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
reg_knn = KNeighborsRegressor()
reg_knn.fit(X_train, y_train)
y_pred = reg_knn.predict(X_test)

mse_knn = mean_squared_error(y_test, y_pred)
print("MSE (KNN):", mse_knn)

MSE (KNN): 18.145584691358017
Mean Squared Error: 18.145584691358017


# Paso 8

In [39]:
import pandas as pd

feature_df = pd.DataFrame({
    "Features": features,
    "Importance": rf.feature_importances_
}).sort_values("Importance", ascending=False)

print(feature_df)


                 Features  Importance
0                Humidity    0.941801
1    Pressure (millibars)    0.029504
3  Wind Bearing (degrees)    0.021651
2         Visibility (km)    0.007044


# Paso 9

In [40]:
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler

# Escalado para modelos basados en distancia/kernels
scaler = StandardScaler().fit(X_train)
Xs_train = scaler.transform(X_train)
Xs_test  = scaler.transform(X_test)

svr = SVR()  
svr.fit(Xs_train, y_train)
print("MSE (SVR):", mean_squared_error(y_test, svr.predict(Xs_test)))

knn = KNeighborsRegressor()
knn.fit(Xs_train, y_train)
print("MSE (KNN):", mean_squared_error(y_test, knn.predict(Xs_test)))

MSE (SVR): 4.044220150319563
MSE (KNN): 3.852949876543213


In [41]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
import numpy as np

# 1) Escalamos X (solo hay que transformar el test)
x_scaler = StandardScaler().fit(X_train)
Xs_train = x_scaler.transform(X_train)
Xs_test  = x_scaler.transform(X_test)

# 2) Escalamos y (hay que recordar la escala para la métrica)
y_scaler = StandardScaler().fit(y_train.reshape(-1, 1))
ys_train = y_scaler.transform(y_train.reshape(-1, 1)).ravel()
ys_test  = y_scaler.transform(y_test.reshape(-1, 1)).ravel()

svr = KNeighborsRegressor()  
svr.fit(Xs_train, ys_train)

# 3a) MSE calculado en la escala estandarizada (adimensional)
mse_scaled = mean_squared_error(ys_test, svr.predict(Xs_test))
print("MSE (KNN, y escalada):", mse_scaled)

# 3b) Invertimos la escala de las predicciones y evaluamos en unidades originales
y_pred_scaled = svr.predict(Xs_test)
y_pred = y_scaler.inverse_transform(y_pred_scaled.reshape(-1, 1)).ravel()
mse_original = mean_squared_error(y_test, y_pred)
print("MSE (KNN, en unidades originales):", mse_original)

MSE (KNN, y escalada): 0.1922876814380746
MSE (KNN, en unidades originales): 3.852949876543211


In [42]:
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
import numpy as np

# 1) Escalamos X (solo hay que transformar el test)
x_scaler = StandardScaler().fit(X_train)
Xs_train = x_scaler.transform(X_train)
Xs_test  = x_scaler.transform(X_test)

# 2) Escalamos y (hay que recordar la escala para la métrica)
y_scaler = StandardScaler().fit(y_train.reshape(-1, 1))
ys_train = y_scaler.transform(y_train.reshape(-1, 1)).ravel()
ys_test  = y_scaler.transform(y_test.reshape(-1, 1)).ravel()

svr = SVR()  
svr.fit(Xs_train, ys_train)

# 3a) MSE calculado en la escala estandarizada (adimensional)
mse_scaled = mean_squared_error(ys_test, svr.predict(Xs_test))
print("MSE (SVR, y escalada):", mse_scaled)

# 3b) Invertimos la escala de las predicciones y evaluamos en unidades originales
y_pred_scaled = svr.predict(Xs_test)
y_pred = y_scaler.inverse_transform(y_pred_scaled.reshape(-1, 1)).ravel()
mse_original = mean_squared_error(y_test, y_pred)
print("MSE (SVR, en unidades originales):", mse_original)


MSE (SVR, y escalada): 0.0473576293307444
MSE (SVR, en unidades originales): 0.9489249166594871


# Paso 10

In [32]:
from sklearn.model_selection import cross_val_score
import numpy as np

scores = cross_val_score(rf, X, y,
                         scoring="neg_mean_squared_error",
                         cv=5)
mse = -scores
print("MSE CV (RF):", mse.mean(), "+/-", mse.std())


MSE CV (RF): 2.7652944322222277 +/- 1.9939869209946917


# Paso 11

In [33]:
from sklearn.model_selection import GridSearchCV

param_grid = {
  "n_estimators": [100, 300, 600],
  "max_depth": [None, 10, 20],
  "min_samples_leaf": [1, 2, 4]
}

gcv = GridSearchCV(
    RandomForestRegressor(random_state=42),
    param_grid=param_grid,
    scoring="neg_mean_squared_error",
    cv=5, n_jobs=-1
)
gcv.fit(X, y)

print("Mejor MSE:", -gcv.best_score_)
print("Mejores params:", gcv.best_params_)

Mejor MSE: 2.5671126949828578
Mejores params: {'max_depth': None, 'min_samples_leaf': 1, 'n_estimators': 600}


# Paso 12

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.compose import ColumnTransformer

pipe = Pipeline(steps=[
    ("scaler", StandardScaler()),
    ("model",  SVR())
])

pipe.fit(X_train, y_train)
print("MSE (Pipeline SVR):",
      mean_squared_error(y_test, pipe.predict(X_test)))


MSE (Pipeline SVR): 12.60673727410281


# Paso 13

In [ ]:
import joblib

joblib.dump(rf, "rf_temperature_model.joblib")
# ...
rf2 = joblib.load("rf_temperature_model.joblib")
